collection_config:
  
  schema_file_glob: ${workspace}/schema/*.schema.xlsx
  data_file_glob: ${workspace}/data/*.data.xlsx
  enum_define_file_glob: ${workspace}/enum/*.enumdefine.yaml

enum_generate_config:

  generate:
    -
      language: csharp
      namespace: Generate

      path: ${workspace}/temp_generate/GenerateEnum.cs

    -
      language: dart
      
      path: ${workspace}/temp_generate/generate_enum.dart

class_generate_config:
  
  - 
    language: csharp

    db_extension: .byte
    namespace: Generate

    generate_path: 
      path: ${workspace}/temp_generate/Tables.g.cs
      usings:
        - System
    
    meta_generate_path: 
      path: ${workspace}/temp_generate/TableMeta.g.cs
      entry_class: GenerateTablesMeta
      entry_name: InitalizeGenerateTableMeta
      usings:
        - System

      meta_collection: TableMetaMapping

  - 
    language: dart

    db_extension: .db

    generate_path: 
      path: ${workspace}/temp_generate/tables.g.dart
      imports:
        - package:tuple/tuple.dart
        - ./base_table.dart
        - ../enum/generate_enum.dart

    meta_generate_path:
      path: ${workspace}/temp_generate/tablemeta.g.dart
      entry_name: initializeTableMeta
      imports:
        - ./base_table_meta.dart
        - ./table.g.dart

      meta_collection: GenerateTableMeta

