#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import sys
import subprocess

#
script_root_path = os.path.dirname(__file__)
script_root_path = os.path.normpath(script_root_path)
script_root_path = os.path.abspath(script_root_path)

cli_root_path, _ = os.path.split(script_root_path)
python_path = '{0}/.env/bin/python3'.format(cli_root_path)

main_path = '{0}/main.py'.format(cli_root_path)
main_path = os.path.normpath(main_path)

cli_argv = [python_path, main_path]

if __name__ == '__main__':

    cli_argv.extend(sys.argv[1:])

    result_code = subprocess.call(cli_argv)
    exit(result_code)
